# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4spqOsAhlIhvCFVVz85oy3q3sLZwpqN
"""

import streamlit as st
import time

# --- Configurações de Negócio ---
# Array corrigido com as 12 notas musicais
NOTAS = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
AFINACAO = ['D', 'G', 'B', 'D'] 
NUM_CASAS = 15 

def gerar_svg_braco(corda_alvo, casa_alvo, nota_alvo, dedo_alvo):
    # Dimensões do desenho
    largura_casa = 45
    altura_corda = 30
    margem_x = 30
    margem_y = 40
    
    largura_total = (NUM_CASAS * largura_casa) + (2 * margem_x)
    altura_total = (3 * altura_corda) + (2 * margem_y)
    
    # Mapeamento de Corda para Y (Corda 1 no topo)
    mapa_y = {"Corda 1": margem_y, "Corda 2": margem_y + altura_corda, 
              "Corda 3": margem_y + (2 * altura_corda), "Corda 4": margem_y + (3 * altura_corda)}
    
    pos_y = mapa_y[corda_alvo]
    pos_x = margem_x + (casa_alvo * largura_casa) - (largura_casa / 2) if casa_alvo > 0 else margem_x - 10

    # Início do SVG
    svg = f'<svg width="100%" viewBox="0 0 {largura_total} {altura_total}" xmlns="http://www.w3.org/2000/svg">'
    
    # Desenho do Braço
    svg += f'<rect x="{margem_x}" y="{margem_y}" width="{NUM_CASAS * largura_casa}" height="{3 * altura_corda}" fill="#3d2b1f" rx="4"/>'
    
    # Desenho dos Trastes (Linhas Verticais) e Numeração
    for c in range(NUM_CASAS + 1):
        x = margem_x + (c * largura_casa)
        cor_traste = "#ffd700" if c == 0 else "#b0b0b0"
        largura_traste = 4 if c == 0 else 1
        svg += f'<line x1="{x}" y1="{margem_y}" x2="{x}" y2="{margem_y + 3 * altura_corda}" stroke="{cor_traste}" stroke-width="{largura_traste}" />'
        svg += f'<text x="{x - largura_casa/2}" y="{margem_y - 10}" font-family="Arial" font-size="12" fill="#888" text-anchor="middle">{c if c > 0 else ""}</text>'

    # Desenho das Cordas (Linhas Horizontais)
    for i in range(4):
        y = margem_y + (i * altura_corda)
        svg += f'<line x1="{margem_x}" y1="{y}" x2="{margem_x + NUM_CASAS * largura_casa}" y2="{y}" stroke="#e0e0e0" stroke-width="{2 + i*0.5}" />'

    # Desenho da Nota Alvo (Onde colocar o dedo)
    cor_nota = "#e74c3c"
    svg += f'<circle cx="{pos_x}" cy="{pos_y}" r="14" fill="{cor_nota}" stroke="white" stroke-width="2" />'
    # Fonte ligeiramente reduzida para caber notas com sustenido (ex: C#|3)
    svg += f'<text x="{pos_x}" y="{pos_y + 4}" font-family="Arial" font-size="11" font-weight="bold" fill="white" text-anchor="middle">{nota_alvo}|{dedo_alvo}</text>'
    
    svg += '</svg>'
    return svg

def gerar_caminho_escala(tom):
    # 1. Encontra a Casa Base na Corda 3
    corda3_notas = [NOTAS[(NOTAS.index('G') + c) % 12] for c in range(NUM_CASAS + 1)]
    try: 
        casa_base = corda3_notas.index(tom)
    except ValueError: 
        casa_base = 5 
    
    if casa_base < 2: 
        casa_base += 12
        
    # 2. Calcula as notas reais da escala escolhida (A CORREÇÃO ESTÁ AQUI)
    intervalos = [0, 2, 4, 5, 7, 9, 11, 12]
    idx_tom = NOTAS.index(tom)
    notas_escala = [NOTAS[(idx_tom + i) % 12] for i in intervalos]
    
    # 3. Shape fechado padrão
    shape = [
        ("Corda 3", 0, 1), ("Corda 3", 2
