# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4spqOsAhlIhvCFVVz85oy3q3sLZwpqN
"""

import streamlit as st
import time

# Configurações Básicas
NOTAS = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
AFINACAO = ['D', 'G', 'B', 'D'] # Cordas 4, 3, 2, 1
NOME_DEDO = {1: "Indicador", 2: "Médio", 3: "Anelar", 4: "Mínimo"}

def gerar_braco(num_casas=12):
    braco = {}
    for i in reversed(range(4)):
        nota_solta = AFINACAO[i]
        idx_inicial = NOTAS.index(nota_solta)
        braco[f"Corda {4-i}"] = [NOTAS[(idx_inicial + casa) % 12] for casa in range(num_casas + 1)]
    return braco

caminho_do_maior = [
    ("Corda 3", 5, "C", 1),
    ("Corda 3", 7, "D", 3),
    ("Corda 2", 5, "E", 1),
    ("Corda 2", 6, "F", 2),
    ("Corda 1", 5, "G", 1),
    ("Corda 1", 7, "A", 3),
    ("Corda 1", 9, "B", 1),
    ("Corda 1", 10, "C", 2)
]

# Configuração da Página Web
st.set_page_config(page_title="Mentor de Cavaquinho", layout="centered")
st.title("🎸 Mentor de Cavaquinho v1.0")
st.markdown("Treino de **Escala Maior (Shape Fechado)** guiado por metrônomo.")

# Controles de Interface
bpm = st.slider("Velocidade do Metrônomo (BPM)", 40, 120, 60)
intervalo = 60 / bpm
dados_braco = gerar_braco(num_casas=12)

# Botão de Ação
if st.button("▶ Iniciar Prática"):
    # Cria um espaço vazio na tela que será sobrescrito a cada loop
    painel = st.empty()

    # Loop do exercício
    for passo, (corda_alvo, casa_alvo, nota_alvo, dedo_alvo) in enumerate(caminho_do_maior):
        with painel.container():
            st.markdown(f"### ⏱️ Passo {passo + 1}/8")
            st.markdown(f"**Alvo:** Nota `{nota_alvo}` na **{corda_alvo}**, Casa **{casa_alvo}**")
            st.markdown(f"**Dedo:** {dedo_alvo} ({NOME_DEDO[dedo_alvo]})")

            # Montando o Grid em formato de texto para manter o alinhamento
            grid = "        |"
            for casa in range(13):
                grid += f"  {casa:^2}  |"
            grid += "\n" + "-" * len(grid) + "\n"

            for corda, notas_na_corda in dados_braco.items():
                linha = f"{corda} |"
                for casa, nota in enumerate(notas_na_corda):
                    if corda == corda_alvo and casa == casa_alvo:
                        texto_celula = f"{nota}|{dedo_alvo}"
                        linha += f"[{texto_celula:^4}]|"
                    else:
                        linha += " ---- |"
                grid += linha + "\n"

            # st.text preserva a fonte monoespaçada, ideal para matrizes/tablaturas
            st.text(grid)

        # Pausa pelo tempo do BPM antes de atualizar a tela novamente
        time.sleep(intervalo)

    painel.success("✅ Exercício finalizado! Respire e clique novamente para repetir.")